version: '3.4'
services:
  nginx:
    image: openresty/openresty:jessie
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - 80:80

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - mezzanine-db-data:/var/lib/postgresql/data/pgdata
  mongo:
    image: mongo
    command: mongod --storageEngine=wiredTiger


  django-mezzanine:
    image: noisy/mezzanine-docker-demo
    ports:
      - 8000:80
    links:
      - db

  django-airflow:
    image: puckel/docker-airflow
    ports:
      - 8080:8080
    command: webserver

  reaction:
    image: reactioncommerce/reaction:latest
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://reaction--${SQUASH_DOMAIN}:3000"
      MONGO_URL: "mongodb://mongo:27017/reaction"
    restart:
      always

volumes:
  mezzanine-db-data:
